package com.mycompany.pcierrecaja;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.CallableStatement;

import com.mycompany.Utils.Utils;
import com.mycompany.Bases.Caja;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.text.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author ba0100069x
 */
public class frmCaja extends javax.swing.JDialog {
    public Utils oUtilidad = new Utils();
    private String sAccion = "N";
    private final  String sBotonesPath = "src\\main\\java\\Iconos\\";
    private final FrmPrincipal mainForm;
 
    /**
     * Creates new form frmAperturaCaja
     * @param parent
     * @param modal
     */
   
    public frmCaja(java.awt.Frame parent, boolean modal)  {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(null);
        this.mainForm = (FrmPrincipal) parent;
        
        //Dibuja los botones
        //String sBotonesPath = "src\\main\\java\\Iconos\\";
        oUtilidad.DibujaImagenToogleButton(tbSalir, "Salir", this.sBotonesPath, "Salir");
        oUtilidad.DibujaImagenToogleButton(tbNuevo, "Nuevo", sBotonesPath, "Nuevo");
        oUtilidad.DibujaImagenToogleButton(tbConsultar, "Buscar", sBotonesPath, "Buscar");
        oUtilidad.DibujaImagenToogleButton(tbGrabar, "Guardar", sBotonesPath, "Guardar");
        oUtilidad.DibujaImagenToogleButton(tbLimpiar, "Limpiar", sBotonesPath, "Limpiar");
        pLimpiar();
        sAccion = "N";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tbSalir = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tbNuevo = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        tbConsultar = new javax.swing.JToggleButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        tbGrabar = new javax.swing.JToggleButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        tbLimpiar = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        txtUbicacion = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Apertura de Caja");

        jToolBar1.setRollover(true);

        tbSalir.setToolTipText("");
        tbSalir.setFocusable(false);
        tbSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(tbSalir);
        jToolBar1.add(jSeparator4);

        tbNuevo.setToolTipText("");
        tbNuevo.setFocusable(false);
        tbNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(tbNuevo);
        jToolBar1.add(jSeparator5);

        tbConsultar.setToolTipText("");
        tbConsultar.setFocusable(false);
        tbConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(tbConsultar);
        jToolBar1.add(jSeparator7);

        tbGrabar.setToolTipText("");
        tbGrabar.setFocusable(false);
        tbGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbGrabarActionPerformed(evt);
            }
        });
        jToolBar1.add(tbGrabar);
        jToolBar1.add(jSeparator6);

        tbLimpiar.setToolTipText("");
        tbLimpiar.setFocusable(false);
        tbLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(tbLimpiar);
        jToolBar1.add(jSeparator1);

        jLabel1.setText("Caja ID:");

        jLabel2.setText("Ubicación:");

        jLabel3.setText("Descripción:");

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUbicacion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tbSalirActionPerformed

    private void tbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNuevoActionPerformed
        // TODO add your handling code here:
         pLimpiar();
         sAccion = "N";
         txtID.setEnabled(false);
    }//GEN-LAST:event_tbNuevoActionPerformed

   
    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void tbGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbGrabarActionPerformed
        try
        {
            sAccion = "G";
            String dbURL = mainForm.VP_URLConexion; //"jdbc:sqlserver://ba0100069x\\SQLEXPRESS;user=sa;password=84+-blaster32;encrypt=true;trustServerCertificate=true;ssl=require;Connect Timeout=0";
            Connection conn = null;
            conn = DriverManager.getConnection(dbURL);
            CallableStatement callableStatement = null;
            Statement statement = null;

            statement = conn.createStatement();
            statement.execute("USE dbVentas");

            String sql = "{call sp_vt_mantenimiento_cajas (?, ?, ?, ?, ?, ?)}";
            callableStatement = conn.prepareCall(sql);

            // Establecer los parámetros de entrada y salida
            callableStatement.registerOutParameter(1, java.sql.Types.INTEGER);  // Parámetro de retorno
            callableStatement.registerOutParameter("o_msgerr", java.sql.Types.VARCHAR);  // Parámetro de salida
            callableStatement.setString("i_opc", sAccion);
            callableStatement.setString("i_ubicacion", txtUbicacion.getText());
            callableStatement.setString("i_descripcion", txtObservacion.getText());
            callableStatement.setString("i_estado", Character.toString(cmbEstado.getSelectedItem().toString().charAt(0)));
            callableStatement.setInt("o_id", Integer.parseInt(txtID.getText()));
            callableStatement.registerOutParameter("o_id", java.sql.Types.SMALLINT);  // Parámetro de salida

            // Ejecutar el stored procedure
            callableStatement.execute();
            
            
            // Obtener el valor de retorno
            int returnValue = callableStatement.getInt(1);      

            //Obtener paametros de salida
            String sMsgErr = callableStatement.getString("o_msgerr");
            int iCaja = callableStatement.getInt("o_id");
            
            if (returnValue != 0) {
                JOptionPane.showMessageDialog(null, sMsgErr, "Cajas", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtID.setText(Integer.toString(iCaja));
            JOptionPane.showMessageDialog(null, "Registro de Caja grabado correctamente", "Cajas", JOptionPane.INFORMATION_MESSAGE);
            
            pLimpiar();
            txtID.setEnabled(true);
            conn.close();
            
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Cajas", JOptionPane.ERROR_MESSAGE);
        }        
        
//        Caja oCaja = new Caja();
//        oCaja.idCaja = Integer.parseInt(txtID.getText());
//        oCaja.Usuario = txtUsuario.getText();
//        oCaja.Observacion = txtObservacion.getText();
//        oCaja.Monto = Double.parseDouble(txtMonto.getText());
        
    }//GEN-LAST:event_tbGrabarActionPerformed

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
        // TODO add your handling code here:
//        sAccion = "C";
//        if (txtID.getText().equals("") || sAccion.equals("N")) {
//            return;
//        }        
//        pConsultar();
        
    }//GEN-LAST:event_txtIDFocusLost

    private void pConsultar() {
        try
        {
            if (txtID.getText().equals("")) {
                return;
            }
            
            String dbURL = mainForm.VP_URLConexion; //"jdbc:sqlserver://ba0100069x\\SQLEXPRESS;database=dbVentas;user=sa;password=84+-blaster32;encrypt=true;trustServerCertificate=true;ssl=require;Connect Timeout=0";
            Connection conn = null;
            conn = DriverManager.getConnection(dbURL);
            
            String sql = "{call sp_vt_mantenimiento_cajas (?, ?, ?, ?, ?, ?)}";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "");
            ps.setString(2, sAccion);
            ps.setString(3, "");
            ps.setString(4, "");
            ps.setString(5, "");
            ps.setInt(6, Integer.parseInt(txtID.getText()));
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                txtUbicacion.setText(rs.getString("ca_ubicacion"));
                txtObservacion.setText(rs.getString("ca_descripcion"));

                int iIndex = -1;
                for (int i = 0; i < cmbEstado.getItemCount(); i++) {
                    if (Character.toString(cmbEstado.getItemAt(i).charAt(0)).equals(rs.getString("ca_estado"))) {
                     iIndex = i;
                     break;
                    }   
                }
                cmbEstado.setSelectedIndex(iIndex);
            }
            txtID.setEnabled(true);
            ps.close();
            rs.close();
            conn.close();
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Cajas", JOptionPane.ERROR_MESSAGE);
        }        
        
        
//        for (Caja oCaja : oListaCaja) {
//            if (oCaja.idCaja == Integer.parseInt(txtID.getText()) ){
//                txtUsuario.setText(oCaja.Usuario.trim());
//                txtObservacion.setText(oCaja.Observacion.trim());
//                txtMonto.setText(Double.toString(oCaja.Monto));
//                bdEncontro = true;
//                break;
//            }        
//        }
//        if (!bdEncontro) {
//            JOptionPane.showMessageDialog(
//                   null, "Código de Caja no Existe " + sAccion, "Cajas", JOptionPane.INFORMATION_MESSAGE);
//            txtID.setEnabled(true);
//            txtID.setText("");
//            txtID.requestFocus();
//        }
    }
    
    private void tbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLimpiarActionPerformed
        // TODO add your handling code here:
        pLimpiar();
        txtID.setEnabled(true);
        txtID.requestFocus();
    }//GEN-LAST:event_tbLimpiarActionPerformed

    private void tbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbConsultarActionPerformed
        // TODO add your handling code here:
        sAccion = "C";
        if (txtID.getText().equals("") || sAccion.equals("N")) {
            return;
        }        
        txtID.setEnabled(false);
        pConsultar();        
        //txtID.setEnabled(false);
    }//GEN-LAST:event_tbConsultarActionPerformed

    private void pLimpiar(){
        txtID.setText("");
        txtUbicacion.setText("");
        txtObservacion.setText("");
        sAccion = "N";    
        //txtID.setEnabled(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create an instance of your custom class (Clase) */
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCaja dialog = new frmCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton tbConsultar;
    private javax.swing.JToggleButton tbGrabar;
    private javax.swing.JToggleButton tbLimpiar;
    private javax.swing.JToggleButton tbNuevo;
    private javax.swing.JToggleButton tbSalir;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables


}
